name: pmir
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.24
  - pandas>=2.0
  - scipy>=1.10
  - matplotlib>=3.7
  - statsmodels>=0.14
  - jupyter
  - ipython
  - pip
  - pip:
    - openpyxl>=3.1.0
